compute_environment: LOCAL_MACHINE
debug: false
distributed_type: NO # Single GPU
# distributed_type: MULTI_GPU # MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: true
gpu_ids: "0" # Single GPU
# gpu_ids: all # Multi GPU
machine_rank: 0
main_training_function: main
main_process_port: 29501
mixed_precision: fp16
num_machines: 1
num_processes: 1 # Single GPU
# num_processes: 2 # Multi GPU
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
